apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mapserver
  template:
    metadata:
      labels:
        app: mapserver
    spec:
      containers:
        #- image: eu.gcr.io/cloudmark2/mapserver:48058be
        - image: eu.gcr.io/cloudmark2/mapserver:a3f696c

          imagePullPolicy: Always
          name: mapserver
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ortho
              mountPath: /srv/ortho
      volumes:
        - name: ortho
          persistentVolumeClaim:
            claimName: ortho
